### ISSUE TITLE
myEpic

### ISSUE THREAD

**Issue by InbalZilberman** [Conjurinc-workato-dev/appliance#62]
### Feature Overview & Customer Need

In Summary, 
**Process Diagram**

**Process Logic \ XDD**

**Configuration ** 

**Open Issues:**

### DOD
- [ ] Implement the feature
- [x] Automatic integration tests written according to a test plan and passed successfully
- [ ] Demo the feature according to requirements/flows
- [x] UT written for all classes\functions\major logic flows and passed successfully
- [ ] Security review has been performed
- [ ] Security action items were taken
- [ ] Enhance logs and supportability - Do we need troubleshooting section?
- [ ] Logs were reviewed by TW and PO
- [ ] Fill in the configurations in feature doc
- [ ] Configurations were reviewed by PO - link if something changed
- [ ] Are there new Audits to this feature? If so please document them and provide here a link
- [ ] Documentation HO to TW and review docs

**Comment by maxAtSW** [comment]
https://ca-il-jira-test.il.cyber-ark.com/browse/ONYX-6710
